using Nursan.Domain.Entity;
using Nursan.Domain.TORKS;
using Nursan.Logging.Messages;
using Nursan.Persistanse.UnitOfWork;

namespace Nursan.Validations.Opsionlar
{
    public class TorkAktar
    {
        readonly UnitOfWork _context;
        readonly NursandatabaseContext _lcContext;
        private IzTorkDeger izTork;
        public TorkAktar(NursandatabaseContext lcContext, UnitOfWork context)
        {
            _lcContext = lcContext;
            _context = context;
        }

        public async Task<bool> ExecuteTorkAktar()
        {
            try
            {
                var gelenveri = _lcContext.Nrsclsdegs.ToList();
                Messaglama.MessagException(gelenveri.Count().ToString());

                foreach (var v in gelenveri)
                {
                    try
                    {
                        Messaglama.MessagException(v.Nr);
                        izTork = new IzTorkDeger
                        {
                            Nr = v.Nr,
                            ReceteName = v.ReceteName,
                            ReceteNo = v.ReceteNo,
                            Kacstep = v.Kacstep,
                            Tork1 = v.Tork1,
                            Aci1 = v.Aci1,
                            Hata1 = v.Hata1,
                            Tabanca1 = v.Tabanca1,
                            Config1 = v.Config1,
                            Kutu1 = v.Kutu1,
                            Vida1 = v.Vida1,
                            Tork2 = v.Tork2,
                            Aci2 = v.Aci2,
                            Hata2 = v.Hata2,
                            Tabanca2 = v.Tabanca2,
                            Config2 = v.Config2,
                            Kutu2 = v.Kutu2,
                            Vida2 = v.Vida2,
                            Tork3 = v.Tork3,
                            Aci3 = v.Aci3,
                            Hata3 = v.Hata3,
                            Tabanca3 = v.Tabanca3,
                            Config3 = v.Config3,
                            Kutu3 = v.Kutu3,
                            Vida3 = v.Vida3,
                            Tork4 = v.Tork4,
                            Aci4 = v.Aci4,
                            Hata4 = v.Hata4,
                            Tabanca4 = v.Tabanca4,
                            Config4 = v.Config4,
                            Kutu4 = v.Kutu4,
                            Vida4 = v.Vida4,
                            Tork5 = v.Tork5,
                            Aci5 = v.Aci5,
                            Hata5 = v.Hata5,
                            Tabanca5 = v.Tabanca5,
                            Config5 = v.Config5,
                            Kutu5 = v.Kutu5,
                            Vida5 = v.Vida5,
                            Tork6 = v.Tork6,
                            Aci6 = v.Aci6,
                            Hata6 = v.Hata6,
                            Tabanca6 = v.Tabanca6,
                            Config6 = v.Config6,
                            Kutu6 = v.Kutu6,
                            Vida6 = v.Vida6,
                            Tork7 = v.Tork7,
                            Aci7 = v.Aci7,
                            Hata7 = v.Hata7,
                            Tabanca7 = v.Tabanca7,
                            Config7 = v.Config7,
                            Kutu7 = v.Kutu7,
                            Vida7 = v.Vida7,
                            Tork8 = v.Tork8,
                            Aci8 = v.Aci8,
                            Hata8 = v.Hata8,
                            Tabanca8 = v.Tabanca8,
                            Config8 = v.Config8,
                            Kutu8 = v.Kutu8,
                            Vida8 = v.Vida8,
                            Tork9 = v.Tork9,
                            Aci9 = v.Aci9,
                            Hata9 = v.Hata9,
                            Tabanca9 = v.Tabanca9,
                            Config9 = v.Config9,
                            Kutu9 = v.Kutu9,
                            Vida9 = v.Vida9,
                            Tork10 = v.Tork10,
                            Aci10 = v.Aci10,
                            Hata10 = v.Hata10,
                            Tabanca10 = v.Tabanca10,
                            Config10 = v.Config10,
                            Kutu10 = v.Kutu10,
                            Vida10 = v.Vida10,
                            Tork11 = v.Tork11,
                            Aci11 = v.Aci11,
                            Hata11 = v.Hata11,
                            Tabanca11 = v.Tabanca11,
                            Config11 = v.Config11,
                            Kutu11 = v.Kutu11,
                            Vida11 = v.Vida11,
                            Tork12 = v.Tork12,
                            Aci12 = v.Aci12,
                            Hata12 = v.Hata12,
                            Tabanca12 = v.Tabanca12,
                            Config12 = v.Config12,
                            Kutu12 = v.Kutu12,
                            Vida12 = v.Vida12,
                            Tork13 = v.Tork13,
                            Aci13 = v.Aci13,
                            Hata13 = v.Hata13,
                            Tabanca13 = v.Tabanca13,
                            Config13 = v.Config13,
                            Kutu13 = v.Kutu13,
                            Vida13 = v.Vida13,
                            Tork14 = v.Tork14,
                            Aci14 = v.Aci14,
                            Hata14 = v.Hata14,
                            Tabanca14 = v.Tabanca14,
                            Config14 = v.Config14,
                            Kutu14 = v.Kutu14,
                            Vida14 = v.Vida14,
                            Tork15 = v.Tork15,
                            Aci15 = v.Aci15,
                            Hata15 = v.Hata15,
                            Tabanca15 = v.Tabanca15,
                            Config15 = v.Config15,
                            Kutu15 = v.Kutu15,
                            Vida15 = v.Vida15,
                            Tork16 = v.Tork16,
                            Aci16 = v.Aci16,
                            Hata16 = v.Hata16,
                            Tabanca16 = v.Tabanca16,
                            Config16 = v.Config16,
                            Kutu16 = v.Kutu16,
                            Vida16 = v.Vida16,
                            Tork17 = v.Tork17,
                            Aci17 = v.Aci17,
                            Hata17 = v.Hata17,
                            Tabanca17 = v.Tabanca17,
                            Config17 = v.Config17,
                            Kutu17 = v.Kutu17,
                            Vida17 = v.Vida17,
                            Tork18 = v.Tork18,
                            Aci18 = v.Aci18,
                            Hata18 = v.Hata18,
                            Tabanca18 = v.Tabanca18,
                            Config18 = v.Config18,
                            Kutu18 = v.Kutu18,
                            Vida18 = v.Vida18,
                            Tork19 = v.Tork19,
                            Aci19 = v.Aci19,
                            Hata19 = v.Hata19,
                            Tabanca19 = v.Tabanca19,
                            Config19 = v.Config19,
                            Kutu19 = v.Kutu19,
                            Vida19 = v.Vida19,
                            Tork20 = v.Tork20,
                            Aci20 = v.Aci20,
                            Hata20 = v.Hata20,
                            Tabanca20 = v.Tabanca20,
                            Config20 = v.Config20,
                            Kutu20 = v.Kutu20,
                            Vida20 = v.Vida20,
                            Tork21 = v.Tork21,
                            Aci21 = v.Aci21,
                            Hata21 = v.Hata21,
                            Tabanca21 = v.Tabanca21,
                            Config21 = v.Config21,
                            Kutu21 = v.Kutu21,
                            Vida21 = v.Vida21,
                            Tork22 = v.Tork22,
                            Aci22 = v.Aci22,
                            Hata22 = v.Hata22,
                            Tabanca22 = v.Tabanca22,
                            Config22 = v.Config22,
                            Kutu22 = v.Kutu22,
                            Vida22 = v.Vida22,
                            Tork23 = v.Tork23,
                            Aci23 = v.Aci23,
                            Hata23 = v.Hata23,
                            Tabanca23 = v.Tabanca23,
                            Config23 = v.Config23,
                            Kutu23 = v.Kutu23,
                            Vida23 = v.Vida23,
                            Tork24 = v.Tork24,
                            Aci24 = v.Aci24,
                            Hata24 = v.Hata24,
                            Tabanca24 = v.Tabanca24,
                            Config24 = v.Config24,
                            Kutu24 = v.Kutu24,
                            Vida24 = v.Vida24,
                            Tork25 = v.Tork25,
                            Aci25 = v.Aci25,
                            Hata25 = v.Hata25,
                            Tabanca25 = v.Tabanca25,
                            Config25 = v.Config25,
                            Kutu25 = v.Kutu25,
                            Vida25 = v.Vida25,
                            Tork26 = v.Tork26,
                            Aci26 = v.Aci26,
                            Hata26 = v.Hata26,
                            Tabanca26 = v.Tabanca26,
                            Config26 = v.Config26,
                            Kutu26 = v.Kutu26,
                            Vida26 = v.Vida26,
                            Tork27 = v.Tork27,
                            Aci27 = v.Aci27,
                            Hata27 = v.Hata27,
                            Tabanca27 = v.Tabanca27,
                            Config27 = v.Config27,
                            Kutu27 = v.Kutu27,
                            Vida27 = v.Vida27,
                            Tork28 = v.Tork28,
                            Aci28 = v.Aci28,
                            Hata28 = v.Hata28,
                            Tabanca28 = v.Tabanca28,
                            Config28 = v.Config28,
                            Kutu28 = v.Kutu28,
                            Vida28 = v.Vida28,
                            Tork29 = v.Tork29,
                            Aci29 = v.Aci29,
                            Hata29 = v.Hata29,
                            Tabanca29 = v.Tabanca29,
                            Config29 = v.Config29,
                            Kutu29 = v.Kutu29,
                            Vida29 = v.Vida29,
                            Tork30 = v.Tork30,
                            Aci30 = v.Aci30,
                            Hata30 = v.Hata30,
                            Tabanca30 = v.Tabanca30,
                            Config30 = v.Config30,
                            Kutu30 = v.Kutu30,
                            Vida30 = v.Vida30,
                            Tork31 = v.Tork31,
                            Aci31 = v.Aci31,
                            Hata31 = v.Hata31,
                            Tabanca31 = v.Tabanca31,
                            Config31 = v.Config31,
                            Kutu31 = v.Kutu31,
                            Vida31 = v.Vida31,
                            Tork32 = v.Tork32,
                            Aci32 = v.Aci32,
                            Hata32 = v.Hata32,
                            Tabanca32 = v.Tabanca32,
                            Config32 = v.Config32,
                            Kutu32 = v.Kutu32,
                            Vida32 = v.Vida32,
                            Tork33 = v.Tork33,
                            Aci33 = v.Aci33,
                            Hata33 = v.Hata33,
                            Tabanca33 = v.Tabanca33,
                            Config33 = v.Config33,
                            Kutu33 = v.Kutu33,
                            Vida33 = v.Vida33,
                            Tork34 = v.Tork34,
                            Aci34 = v.Aci34,
                            Hata34 = v.Hata34,
                            Tabanca34 = v.Tabanca34,
                            Config34 = v.Config34,
                            Kutu34 = v.Kutu34,
                            Vida34 = v.Vida34,
                            Tork35 = v.Tork35,
                            Aci35 = v.Aci35,
                            Hata35 = v.Hata35,
                            Tabanca35 = v.Tabanca35,
                            Config35 = v.Config35,
                            Kutu35 = v.Kutu35,
                            Vida35 = v.Vida35,
                            Tork36 = v.Tork36,
                            Aci36 = v.Aci36,
                            Hata36 = v.Hata36,
                            Tabanca36 = v.Tabanca36,
                            Config36 = v.Config36,
                            Kutu36 = v.Kutu36,
                            Vida36 = v.Vida36,
                            Tork37 = v.Tork37,
                            Aci37 = v.Aci37,
                            Hata37 = v.Hata37,
                            Tabanca37 = v.Tabanca37,
                            Config37 = v.Config37,
                            Kutu37 = v.Kutu37,
                            Vida37 = v.Vida37,
                            Tork38 = v.Tork38,
                            Aci38 = v.Aci38,
                            Hata38 = v.Hata38,
                            Tabanca38 = v.Tabanca38,
                            Config38 = v.Config38,
                            Kutu38 = v.Kutu38,
                            Vida38 = v.Vida38,
                            Tork39 = v.Tork39,
                            Aci39 = v.Aci39,
                            Hata39 = v.Hata39,
                            Tabanca39 = v.Tabanca39,
                            Config39 = v.Config39,
                            Kutu39 = v.Kutu39,
                            Vida39 = v.Vida39,
                            Tork40 = v.Tork40,
                            Aci40 = v.Aci40,
                            Hata40 = v.Hata40,
                            Tabanca40 = v.Tabanca40,
                            Config40 = v.Config40,
                            Kutu40 = v.Kutu40,
                            Vida40 = v.Vida40,
                            Tork41 = v.Tork41,
                            Aci41 = v.Aci41,
                            Hata41 = v.Hata41,
                            Tabanca41 = v.Tabanca41,
                            Config41 = v.Config41,
                            Kutu41 = v.Kutu41,
                            Vida41 = v.Vida41,
                            Tork42 = v.Tork42,
                            Aci42 = v.Aci42,
                            Hata42 = v.Hata42,
                            Tabanca42 = v.Tabanca42,
                            Config42 = v.Config42,
                            Kutu42 = v.Kutu42,
                            Vida42 = v.Vida42,
                            Tork43 = v.Tork43,
                            Aci43 = v.Aci43,
                            Hata43 = v.Hata43,
                            Tabanca43 = v.Tabanca43,
                            Config43 = v.Config43,
                            Kutu43 = v.Kutu43,
                            Vida43 = v.Vida43,
                            Tork44 = v.Tork44,
                            Aci44 = v.Aci44,
                            Hata44 = v.Hata44,
                            Tabanca44 = v.Tabanca44,
                            Config44 = v.Config44,
                            Kutu44 = v.Kutu44,
                            Vida44 = v.Vida44,
                            Tork45 = v.Tork45,
                            Aci45 = v.Aci45,
                            Hata45 = v.Hata45,
                            Tabanca45 = v.Tabanca45,
                            Config45 = v.Config45,
                            Kutu45 = v.Kutu45,
                            Vida45 = v.Vida45,
                            Tork46 = v.Tork46,
                            Aci46 = v.Aci46,
                            Hata46 = v.Hata46,
                            Tabanca46 = v.Tabanca46,
                            Config46 = v.Config46,
                            Kutu46 = v.Kutu46,
                            Vida46 = v.Vida46,
                            Tork47 = v.Tork47,
                            Aci47 = v.Aci47,
                            Hata47 = v.Hata47,
                            Tabanca47 = v.Tabanca47,
                            Config47 = v.Config47,
                            Kutu47 = v.Kutu47,
                            Vida47 = v.Vida47,
                            Tork48 = v.Tork48,
                            Aci48 = v.Aci48,
                            Hata48 = v.Hata48,
                            Tabanca48 = v.Tabanca48,
                            Config48 = v.Config48,
                            Kutu48 = v.Kutu48,
                            Vida48 = v.Vida48,
                            Tork49 = v.Tork49,
                            Aci49 = v.Aci49,
                            Hata49 = v.Hata49,
                            Tabanca49 = v.Tabanca49,
                            Config49 = v.Config49,
                            Kutu49 = v.Kutu49,
                            Vida49 = v.Vida49,
                            Tork50 = v.Tork50,
                            Aci50 = v.Aci50,
                            Hata50 = v.Hata50,
                            Tabanca50 = v.Tabanca50,
                            Config50 = v.Config50,
                            Kutu50 = v.Kutu50,
                            Vida50 = v.Vida50,
                            Calisan = v.Calisan,
                            Makine = Environment.MachineName,
                            Tarih = $"{DateTime.UtcNow.Year.ToString()}-{DateTime.UtcNow.Month.ToString()}-{DateTime.UtcNow.Day.ToString()}",
                            Saat = $"{DateTime.UtcNow.Hour.ToString()}:{DateTime.UtcNow.Minute.ToString()}:{DateTime.UtcNow.Second.ToString()}",
                            Activ = true,
                            CreateDate = DateTime.UtcNow,
                            UpdateDate = DateTime.UtcNow
                        };
                        _context.GetRepository<IzTorkDeger>().Add(izTork);
                        Messaglama.MessagException(v.Nr + "1");
                        _lcContext.Remove(v);
                        _lcContext.SaveChanges();
                        Messaglama.MessagException(v.Nr + "2");

                    }
                    catch (Exception ex)
                    {
                        Messaglama.MessagException(ex.Message);
                    }
                }
            }
            catch (Exception ex)
            {
                Messaglama.MessagException(ex.Message);
            }
            return true;
        }
    }
}
